export default {
  '/': 'links.home',
  '/single': 'links.single',
  '/group': 'links.group',
  '/income': 'links.income',
  '/refresh': 'links.refresh',
  '/este': 'links.este',
  '/categories': 'links.categories',
  '/categories/edit': 'links.categories.edit',
  '/todos': 'links.todos',
  '/fields': 'links.fields',
  '/intl': 'links.intl',
  '/offline': 'links.offline',
  '/me': 'links.me',
  '/settings': 'links.settings',
}
